[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
src_paths = ["zucker", "tests"]

[tool.black]
line-length = 88
target-version = ['py38']
include = "/(zucker|tests)/.*\\.pyi?$"
