name: "Tests and style linting"

on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        name: zucker
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: 'zucker-.+-checks$'
    - run: nix flake check
