name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - id: build-docs
      run: |
        nix build .#docs
    - if: success()
      uses: yrd/ghaction-github-pages@d57754dd075c95169e49d25d23d2c07d64de4c53
      with:
        target_branch: gh-pages
        build_dir: result
        follow_symlinks: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
